language: node_js
node_js:
- 4.2.2
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
- npm run-script lint
env:
  global:
  - CXX=g++-4.8
  - secure: iHuEaZmfBpdYOd345gPBRI17wdXqSYmlbCUskJeTBC8/kgEE1f4NQXP66U1oUq4md+jefIFVIyJWZRQYiHefUaAa0v5twIU3VOJu6xXw473iJiyULAqOKNiXd2ZLgRwlLdQbB3Rj+F5QVQqFGtd2U+ilGGhueOdOjLDcozovO1+SYWWGoYyq74IIPd2Aj+dafBxrz6LM0hRrXlWu9MlW5u1oSMKGRQTRGj2w9jnXzXdX6eiIXUVbQCnJcnkztzE8Y8xKomGz8j+SllMK+GxZ+OizVobnkTQBaGCf5hX4T3xPKQDwJgkG0VeBqM+h+x3MbVMBgMooun7pvuAmFhkdSz7fgb2AjpznR+2hNoGrWBAvJjpSltessIqFxL6JHuqCxnffEfbaby9kuQaPNVdbdNn/eI6OkUpNr+3TkVD4l0qdelk18pNRwCYdY8NkzBGpMajRcodgh1R66mCNaZp6hNQVDU1tsZKnhc6QK+rcEvhxzq9xLdiSYKxEmmUMzDs7Xo53kJloqhp1UVcd/DiDXRLN7WfIzAU/d4c4KfJuvY8Ykcp/rxNCFdc7fIAJ5s7h0kulfD2q8MQajh72ZOBr1bVneGMBTjyTHkCQHhiW1XgooecAIFXyoJgjVwmRPI7Aw0newoKJ+2bRXqZubsgQuableWPdl6WQy7tBlEUyB70=
  - secure: WvOCDM+VdueJaUD8t2UVH671mc5zHuciQDwsJUgNFBVyYFdW6bo/TUBXU60EnSxWFO0MMPo55UCwmtOty0cBcDyNNycU/Cpq5wCavFCNqHZYxL8N2qGDJgs1FlhaP6aiI2bUOFpreBNTtuCg1wUX0JU4VK0Z0ijnOj5pgdwTMhLRoCK5/f3MoMq7C3IdsUhpUuUBwyXMjIEJHsp6wnUfMqYr0FcSL0TzrEuCnkgqkPgs/vfRbNJdRNLfCjASShC+NQTfz7W2dD33yy5W7X3HF9TF5UfhEcC8bt01FGo1T+QB4A2yqB9OzXf0w86bjtP4bJul61f39Hyhfn4Tt1tc1tqe6sDZiMh6F/hIhPXu5AIHIOeU4eQ6Yigs2LtTnIozMG0ZOWF/gfeBF43Mh/nvKi6PA7LwlAv2q1KaoWw2JAJaOQRobUHHeSBgD3qMrf3spl4XYTt2zLt8DB36FOl5a1hczbdw8lI1L5XtY4CwYgI29p+U6r2mtJMw0eZdw+Yv9fXi715oVH1neW1cHFckk1U6J49fWnMl2LVM0n/F5jagJbAEVvmLdUvt6jXt06WJMWZUB6HHWRswlqJjw6cfQt4bcFp9MiYsGPyrJ9dkFIQUwzi2qVQrqZfGmXPDoo3KrbZNECivlAJd98qcvfJP1bfC+W1qJPxTWNVCTJxcxoQ=
notifications:
  slack:
    secure: KpMEfM6BPCmcHQsFM/RfMwxUVujTCRY3nolMnQ8MllK04TXZswW7qwtdb32jSpja2N0F3CUx/UEeushpdQ51eD+XqFnpioPFUzoTm+vmAza6QiXvQDGAMIF688BMjlR/BeCIVL7BwEUd5vBv2G0nh9hgqE2ItBc4X9UoMikn+StiNuVwHP9WHJ2GpLW9ft9TPXyUrtNsaIhQ3AJCJyBO0H+HZpK8AaTv/IA+rcfcvv73mB4LzK6o4PxfIeJAE2NeW9v0+pNlQ7obQVmltAvOd3W6mWgVvYA0I0NJN0LCRd5LFzf/uQQAh1n4oUgnAnQKUWBckcWRnznx14r1LWRyRgZMIJdGCKpn+MQPl2I8WHnHgl1YRxFxD9JjPHquoe7tPlbbaenj7eC8By7s+Q7gog6F4h6Df0JsiRtfg/fuGkLukqAfWrrTND9T3EIZCL6k4HtpLvvfG1pz9kRIKco2lUKyqZUeZYuimElmZ9Pw7wiUogfhjfnMGWzpERNwZewGt7LDNSNy9nLjzGd36IrqXjE+4rwKkZ6/Bcv8/zh1KCRBxT+3OT4a7c4RmJ9ay+thzbJVatwzUYZ4GQE3cw196I1MJUnDMpqm0z0BRxWvtdZfA/Jo97HVfPsC43R8VDNBzXfZLLryCj9FIKUrX84yAI3/4dUe5Nef2mp6YewXAGU=
