# This file has been generated by node2nix 1.3.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@purest/providers-1.0.0" = {
      name = "@purest/providers";
      packageName = "@purest/providers";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@purest/providers/-/providers-1.0.0.tgz";
        sha1 = "8847582c302f12609af8f4c8d1974dc1b034c317";
      };
    };
    "atob-2.0.3" = {
      name = "atob";
      packageName = "atob";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/atob/-/atob-2.0.3.tgz";
        sha1 = "19c7a760473774468f20b2d2d03372ad7d4cbf5d";
      };
    };
    "aws-sdk-2.145.0" = {
      name = "aws-sdk";
      packageName = "aws-sdk";
      version = "2.145.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.145.0.tgz";
        sha1 = "085bb4553231defd93b96b0d95023717c9c3c093";
      };
    };
    "body-parser-1.15.2" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.15.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.15.2.tgz";
        sha1 = "d7578cf4f1d11d5f6ea804cef35dc7a7ff6dae67";
      };
    };
    "commander-2.9.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.9.0.tgz";
        sha1 = "9c99094176e12240cb22d6c5146098400fe0f7d4";
      };
    };
    "connect-redis-3.3.2" = {
      name = "connect-redis";
      packageName = "connect-redis";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect-redis/-/connect-redis-3.3.2.tgz";
        sha512 = "3w8bsdsqpz407jwgac2qa2lp08551xlqmsfyps1q7p0c80lx1dwip148rjc5fgm5w845al5c30i6rypggp4h6nhqzdk1jf0vyagbrkc";
      };
    };
    "cookie-parser-1.4.3" = {
      name = "cookie-parser";
      packageName = "cookie-parser";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-parser/-/cookie-parser-1.4.3.tgz";
        sha1 = "0fe31fa19d000b95f4aadf1f53fdc2b8a203baa5";
      };
    };
    "express-4.14.0" = {
      name = "express";
      packageName = "express";
      version = "4.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.14.0.tgz";
        sha1 = "c1ee3f42cdc891fb3dc650a8922d51ec847d0d66";
      };
    };
    "express-prom-bundle-3.2.1" = {
      name = "express-prom-bundle";
      packageName = "express-prom-bundle";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/express-prom-bundle/-/express-prom-bundle-3.2.1.tgz";
        sha512 = "20qi3d0byr938sfhkvhwh54l8aj88zvzrd052g4j29l16hiac08cnckjg9sipszf8gdgvi9nhk9yql4ji0vf0vj09l1q54sl768y8k6";
      };
    };
    "express-session-1.14.2" = {
      name = "express-session";
      packageName = "express-session";
      version = "1.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/express-session/-/express-session-1.14.2.tgz";
        sha1 = "6bcf586ed6d1dc37b02570087756c9de7b80b275";
      };
    };
    "grant-express-3.7.0" = {
      name = "grant-express";
      packageName = "grant-express";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grant-express/-/grant-express-3.7.0.tgz";
        sha1 = "25f694f11fbc97df81e821052747191a286cf881";
      };
    };
    "helmet-3.3.0" = {
      name = "helmet";
      packageName = "helmet";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/helmet/-/helmet-3.3.0.tgz";
        sha1 = "8eec02d8191ba97a6bdeccbf35f38326285136fd";
      };
    };
    "jsonwebtoken-8.1.0" = {
      name = "jsonwebtoken";
      packageName = "jsonwebtoken";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-8.1.0.tgz";
        sha1 = "c6397cd2e5fd583d65c007a83dc7bb78e6982b83";
      };
    };
    "lodash.merge-4.6.0" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.0.tgz";
        sha1 = "69884ba144ac33fe699737a6086deffadd0f89c5";
      };
    };
    "mime-types-2.1.12" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.12.tgz";
        sha1 = "152ba256777020dd4663f54c2e7bc26381e71729";
      };
    };
    "morgan-1.8.2" = {
      name = "morgan";
      packageName = "morgan";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/morgan/-/morgan-1.8.2.tgz";
        sha1 = "784ac7734e4a453a9c6e6e8680a9329275c8b687";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "prom-client-10.2.2" = {
      name = "prom-client";
      packageName = "prom-client";
      version = "10.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prom-client/-/prom-client-10.2.2.tgz";
        sha512 = "10kajlw0p53w64d1iy1y4rq8937jn4d18a3v6f352fm9rgz7xhcd6r3iimqi6a0d1m3n2x7b3saxmp2jxiwv5gmsds9ra9mmq284ykp";
      };
    };
    "purest-3.0.0" = {
      name = "purest";
      packageName = "purest";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/purest/-/purest-3.0.0.tgz";
        sha1 = "cc2b4c304045c7f8a9b5ff24e69808da9a76a5dc";
      };
    };
    "redis-2.8.0" = {
      name = "redis";
      packageName = "redis";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis/-/redis-2.8.0.tgz";
        sha512 = "3a3044ax6qdvss83xgjfx10h5q91ls0mwgs3wpsnxcdsiipq3cnmqzsh6glyq0r7vsmpw49jp84c2jnfrhi2bgycrkd9hhhf6ia8lrk";
      };
    };
    "request-2.83.0" = {
      name = "request";
      packageName = "request";
      version = "2.83.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.83.0.tgz";
        sha512 = "0by1djkn836sqd9pk2c777wcjvp34qbk1plx7s4lmykljrblpjc64dvn6ni2vyxsbyk33wnl6avym8vgw0ggr4226xakck8mw7y07cm";
      };
    };
    "tus-js-client-1.4.3" = {
      name = "tus-js-client";
      packageName = "tus-js-client";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tus-js-client/-/tus-js-client-1.4.3.tgz";
        sha1 = "e43375e9a1a42b6fa8da96cf59ab38bea40bc1d9";
      };
    };
    "uuid-2.0.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-2.0.2.tgz";
        sha1 = "48bd5698f0677e3c7901a1c46ef15b1643794726";
      };
    };
    "validator-9.1.1" = {
      name = "validator";
      packageName = "validator";
      version = "9.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-9.1.1.tgz";
        sha512 = "0fsvrxq6ygsn576l2x6i4yr0gaqyzzg5hliqj10hx0h18z6k0rwzd0qjcwx0j1nw8iwlaqhhnl413wwpmpsxga6f3k5g2laa5gqccfm";
      };
    };
    "ws-1.1.1" = {
      name = "ws";
      packageName = "ws";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-1.1.1.tgz";
        sha1 = "082ddb6c641e85d4bb451f03d52f06eabdb1f018";
      };
    };
    "buffer-4.9.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "4.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-4.9.1.tgz";
        sha1 = "6d1bb601b07a4efced97094132093027c95bc298";
      };
    };
    "crypto-browserify-1.0.9" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-1.0.9.tgz";
        sha1 = "cc5449685dfb85eb11c9828acc7cb87ab5bbfcc0";
      };
    };
    "events-1.1.1" = {
      name = "events";
      packageName = "events";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-1.1.1.tgz";
        sha1 = "9ebdb7635ad099c70dcc4c2a1f5004288e8bd924";
      };
    };
    "jmespath-0.15.0" = {
      name = "jmespath";
      packageName = "jmespath";
      version = "0.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jmespath/-/jmespath-0.15.0.tgz";
        sha1 = "a3f222a9aae9f966f5d27c796510e28091764217";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "sax-1.2.1" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.1.tgz";
        sha1 = "7b8e656190b228e81a66aea748480d828cd2d37a";
      };
    };
    "url-0.10.3" = {
      name = "url";
      packageName = "url";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.10.3.tgz";
        sha1 = "021e4d9c7705f21bbf37d03ceb58767402774c64";
      };
    };
    "uuid-3.1.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz";
        sha512 = "3x5mi85l1559nkb35pfksjjgiyfyqrcvmcf0nly1xjl1kb0d37jnxd6sk0b8d331waadnqbf60nfssb563x9pvnjcw87lrh976sv18c";
      };
    };
    "xml2js-0.4.17" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.17.tgz";
        sha1 = "17be93eaae3f3b779359c795b419705a8817e868";
      };
    };
    "xmlbuilder-4.2.1" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-4.2.1.tgz";
        sha1 = "aa58a3041a066f90eaa16c2f5389ff19f3f461a5";
      };
    };
    "base64-js-1.2.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.2.1.tgz";
        sha512 = "0dhi66vsajfcm04s11xqklh5lj3abs4ncnl8h3689964aqam3ps9spmc454hz94rz3x1x5l1ad03jrba67mq9zc9vq9a1gchma581bp";
      };
    };
    "ieee754-1.1.8" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.8.tgz";
        sha1 = "be33d40ac10ef1926701f6f08a2d86fbfd1ad3e4";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "bytes-2.4.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-2.4.0.tgz";
        sha1 = "7d97196f9d5baf7f6935e25985549edd2a6c2339";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "1f4y61wc913jrnga7nny83gzf9l2488q6sl1ry9lbwgh5x5d3va0xcc0xrmjk6gdxl6d4r6rsk800xp5bazhjrx05yx1wpc8c8gg0w4";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "depd-1.1.1" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.1.tgz";
        sha1 = "5783b4e1c459f06fa5ca27f991f3d06e7a310359";
      };
    };
    "http-errors-1.5.1" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.5.1.tgz";
        sha1 = "788c0d2c1de2c81b9e6e8c01843b6b97eb920750";
      };
    };
    "iconv-lite-0.4.13" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.13.tgz";
        sha1 = "1f88aba4ab0b1508e8312acc39345f36e992e2f2";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "qs-6.2.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.0.tgz";
        sha1 = "3b7848c03c2dece69a9522b0fae8c4126d745f3b";
      };
    };
    "raw-body-2.1.7" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.1.7.tgz";
        sha1 = "adfeace2e4fb3098058014d08c072dcc59758774";
      };
    };
    "type-is-1.6.15" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.15.tgz";
        sha1 = "cab10fb4909e441c82842eafe1ad646c81804410";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "setprototypeof-1.0.2" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.2.tgz";
        sha1 = "81a552141ec104b88e89ce383103ad5c66564d08";
      };
    };
    "statuses-1.4.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz";
        sha512 = "1xxwqpj713rq1idbmp7mj7cj9dl52lazgpd5x8a9g88jawbkn9xpwbgljl7cvnd0jqkll2zpdj5xy63dlis9l2k8vmx1n1gvyv8456f";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "mime-types-2.1.17" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz";
        sha1 = "09d7a393f03e995a79f8af857b70a9e0ab16557a";
      };
    };
    "mime-db-1.30.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz";
        sha1 = "74c643da2dd9d6a45399963465b26d5ca7d71f01";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "3g1hqsahr1ks2kpvdxrwzr57fj90nnr0hvwwrw8yyyzcv3i11sym8zwibxx67bl1mln0acddrzpkkdjjxnc6n2cm9fazmgzzsl1fzrr";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "accepts-1.3.4" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.4.tgz";
        sha1 = "86246758c7dd6d21a6474ff084a4740ec05eb21f";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "content-disposition-0.5.1" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.1.tgz";
        sha1 = "87476c6a67c8daa87e32e87616df883ba7fb071b";
      };
    };
    "encodeurl-1.0.1" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.1.tgz";
        sha1 = "79e3d58655346909fe6f0f45a5de68103b294d20";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.7.0" = {
      name = "etag";
      packageName = "etag";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.7.0.tgz";
        sha1 = "03d30b5f67dd6e632d2945d30d6652731a34d5d8";
      };
    };
    "finalhandler-0.5.0" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-0.5.0.tgz";
        sha1 = "e9508abece9b6dba871a6942a1d7911b91911ac7";
      };
    };
    "fresh-0.3.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.3.0.tgz";
        sha1 = "651f838e22424e7566de161d8358caa199f83d4f";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "parseurl-1.3.2" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz";
        sha1 = "fc289d4ed8993119460c156253262cdc8de65bf3";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "proxy-addr-1.1.5" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.1.5.tgz";
        sha1 = "71c0ee3b102de3f202f3b64f608d173fcba1a918";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "send-0.14.1" = {
      name = "send";
      packageName = "send";
      version = "0.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.14.1.tgz";
        sha1 = "a954984325392f51532a7760760e459598c89f7a";
      };
    };
    "serve-static-1.11.2" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.11.2.tgz";
        sha1 = "2cf9889bd4435a320cc36895c9aa57bd662e6ac7";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "statuses-1.3.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.3.1.tgz";
        sha1 = "faf51b9eb74aaef3b3acf4ad5f61abf24cb7b93e";
      };
    };
    "forwarded-0.1.2" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.2.tgz";
        sha1 = "98c23dab1175657b8c0573e8ceccd91b0ff18c84";
      };
    };
    "ipaddr.js-1.4.0" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.4.0.tgz";
        sha1 = "296aca878a821816e5b85d0a285a99bcff4582f0";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "send-0.14.2" = {
      name = "send";
      packageName = "send";
      version = "0.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.14.2.tgz";
        sha1 = "39b0438b3f510be5dc6f667a11f71689368cdeef";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "url-value-parser-1.0.0" = {
      name = "url-value-parser";
      packageName = "url-value-parser";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-value-parser/-/url-value-parser-1.0.0.tgz";
        sha1 = "f909af662f47ad16e4f6a508ea579a695305f0d3";
      };
    };
    "crc-3.4.1" = {
      name = "crc";
      packageName = "crc";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc/-/crc-3.4.1.tgz";
        sha1 = "65d5830b1a2569557cfb324c0e679998521473ee";
      };
    };
    "on-headers-1.0.1" = {
      name = "on-headers";
      packageName = "on-headers";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-headers/-/on-headers-1.0.1.tgz";
        sha1 = "928f5d0f470d49342651ea6794b0857c100693f7";
      };
    };
    "uid-safe-2.1.5" = {
      name = "uid-safe";
      packageName = "uid-safe";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-safe/-/uid-safe-2.1.5.tgz";
        sha512 = "2h6492mk9v9dzy26i5wfajinhi2pg729ksbcsmm0sp8s32hlr432q19g97qghfp5x98hsm77hmzwdzhgi3vhm2drz53ax7rabhydw98";
      };
    };
    "random-bytes-1.0.0" = {
      name = "random-bytes";
      packageName = "random-bytes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-bytes/-/random-bytes-1.0.0.tgz";
        sha1 = "4f68a1dc0ae58bd3fb95848c30324db75d64360b";
      };
    };
    "grant-3.7.0" = {
      name = "grant";
      packageName = "grant";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grant/-/grant-3.7.0.tgz";
        sha1 = "729e42a1b1c05cc0ac917ef49f50fde16be8385b";
      };
    };
    "request-2.74.0" = {
      name = "request";
      packageName = "request";
      version = "2.74.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.74.0.tgz";
        sha1 = "7693ca768bbb0ea5c8ce08c084a45efa05b892ab";
      };
    };
    "qs-6.2.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.1.tgz";
        sha1 = "ce03c5ff0935bc1d9d69a9f14cbd18e568d67625";
      };
    };
    "deep-copy-1.4.0" = {
      name = "deep-copy";
      packageName = "deep-copy";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-copy/-/deep-copy-1.4.0.tgz";
        sha512 = "391lfg3zg5b6grzv9c7abqab7wl46qkja0s12shfwkc9jrld95jvv3radkjsckrxy2nlnq16xc0m6dzvvmnga1fh5dkk0qk0zzbx77z";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "bl-1.1.2" = {
      name = "bl";
      packageName = "bl";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.1.2.tgz";
        sha1 = "fdca871a99713aa00d19e3bbba41c44787a65398";
      };
    };
    "caseless-0.11.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz";
        sha1 = "715b96ea9841593cc33067923f5ec60ebda4f7d7";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-1.0.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-1.0.1.tgz";
        sha1 = "ae315db9a4907fa065502304a66d7733475ee37c";
      };
    };
    "har-validator-2.0.6" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz";
        sha1 = "cdcbc08188265ad119b6a5a7c8ab70eecfb5d27d";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "node-uuid-1.4.8" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.8.tgz";
        sha1 = "b040eb0923968afabf8d32fb1f17f1167fdab907";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.3.tgz";
        sha1 = "0b618a5565b6dea90bf3425d04d55edc475a7561";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "async-2.5.0" = {
      name = "async";
      packageName = "async";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.5.0.tgz";
        sha512 = "1ijrwmifg76a8wwhhfqxg23kd0rsjhzklwvj2czvqxs2k25ii6p3y6s3vhbcc5hnr87b0gfc4nb54b8bph2hn9c6z1f6nldjw04ksbv";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "is-my-json-valid-2.16.1" = {
      name = "is-my-json-valid";
      packageName = "is-my-json-valid";
      version = "2.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-my-json-valid/-/is-my-json-valid-2.16.1.tgz";
        sha512 = "2wmvqb2vfzjbnd2znxkg4sqpksxb9mi1lbr4r5zv535ykxzfv8dbnafra1lhk415wrbg9r1lfhyimcw5xfj3k4ry7inbmcjlnr4zj51";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "generate-function-2.0.0" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz";
        sha1 = "6858fe7c0969b7d4e9093337647ac79f60dfbe74";
      };
    };
    "generate-object-property-1.2.0" = {
      name = "generate-object-property";
      packageName = "generate-object-property";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz";
        sha1 = "9c0e1c40308ce804f4783618b937fa88f99d50d0";
      };
    };
    "jsonpointer-4.0.1" = {
      name = "jsonpointer";
      packageName = "jsonpointer";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-4.0.1.tgz";
        sha1 = "4fd92cb34e0e9db3c89c8622ecf51f9b978c6cb9";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha1 = "57fe1c4e48474edd65b09911f26b1cd4095dda84";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "sshpk-1.13.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz";
        sha1 = "512df6da6287144316dc4c18fe1cf1d940739be3";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "connect-3.5.0" = {
      name = "connect";
      packageName = "connect";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect/-/connect-3.5.0.tgz";
        sha1 = "b357525a0b4c1f50599cd983e1d9efeea9677198";
      };
    };
    "dns-prefetch-control-0.1.0" = {
      name = "dns-prefetch-control";
      packageName = "dns-prefetch-control";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dns-prefetch-control/-/dns-prefetch-control-0.1.0.tgz";
        sha1 = "60ddb457774e178f1f9415f0cabb0e85b0b300b2";
      };
    };
    "dont-sniff-mimetype-1.0.0" = {
      name = "dont-sniff-mimetype";
      packageName = "dont-sniff-mimetype";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dont-sniff-mimetype/-/dont-sniff-mimetype-1.0.0.tgz";
        sha1 = "5932890dc9f4e2f19e5eb02a20026e5e5efc8f58";
      };
    };
    "frameguard-3.0.0" = {
      name = "frameguard";
      packageName = "frameguard";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/frameguard/-/frameguard-3.0.0.tgz";
        sha1 = "7bcad469ee7b96e91d12ceb3959c78235a9272e9";
      };
    };
    "helmet-csp-2.2.0" = {
      name = "helmet-csp";
      packageName = "helmet-csp";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/helmet-csp/-/helmet-csp-2.2.0.tgz";
        sha1 = "047888d9e04018dfbaddcf3a2eaa26865b3683f2";
      };
    };
    "hide-powered-by-1.0.0" = {
      name = "hide-powered-by";
      packageName = "hide-powered-by";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hide-powered-by/-/hide-powered-by-1.0.0.tgz";
        sha1 = "4a85ad65881f62857fc70af7174a1184dccce32b";
      };
    };
    "hpkp-2.0.0" = {
      name = "hpkp";
      packageName = "hpkp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hpkp/-/hpkp-2.0.0.tgz";
        sha1 = "10e142264e76215a5d30c44ec43de64dee6d1672";
      };
    };
    "hsts-2.0.0" = {
      name = "hsts";
      packageName = "hsts";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hsts/-/hsts-2.0.0.tgz";
        sha1 = "a52234c6070decf214b2b6b70bb144d07e4776c7";
      };
    };
    "ienoopen-1.0.0" = {
      name = "ienoopen";
      packageName = "ienoopen";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ienoopen/-/ienoopen-1.0.0.tgz";
        sha1 = "346a428f474aac8f50cf3784ea2d0f16f62bda6b";
      };
    };
    "nocache-2.0.0" = {
      name = "nocache";
      packageName = "nocache";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nocache/-/nocache-2.0.0.tgz";
        sha1 = "202b48021a0c4cbde2df80de15a17443c8b43980";
      };
    };
    "referrer-policy-1.1.0" = {
      name = "referrer-policy";
      packageName = "referrer-policy";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/referrer-policy/-/referrer-policy-1.1.0.tgz";
        sha1 = "35774eb735bf50fb6c078e83334b472350207d79";
      };
    };
    "x-xss-protection-1.0.0" = {
      name = "x-xss-protection";
      packageName = "x-xss-protection";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/x-xss-protection/-/x-xss-protection-1.0.0.tgz";
        sha1 = "898afb93869b24661cf9c52f9ee8db8ed0764dd9";
      };
    };
    "camelize-1.0.0" = {
      name = "camelize";
      packageName = "camelize";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelize/-/camelize-1.0.0.tgz";
        sha1 = "164a5483e630fa4321e5af07020e531831b2609b";
      };
    };
    "content-security-policy-builder-1.1.0" = {
      name = "content-security-policy-builder";
      packageName = "content-security-policy-builder";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-security-policy-builder/-/content-security-policy-builder-1.1.0.tgz";
        sha1 = "d91f1b076236c119850c7dee9924bf55e05772b3";
      };
    };
    "dasherize-2.0.0" = {
      name = "dasherize";
      packageName = "dasherize";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dasherize/-/dasherize-2.0.0.tgz";
        sha1 = "6d809c9cd0cf7bb8952d80fc84fa13d47ddb1308";
      };
    };
    "lodash.reduce-4.6.0" = {
      name = "lodash.reduce";
      packageName = "lodash.reduce";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.reduce/-/lodash.reduce-4.6.0.tgz";
        sha1 = "f1ab6b839299ad48f784abbf476596f03b914d3b";
      };
    };
    "platform-1.3.1" = {
      name = "platform";
      packageName = "platform";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/platform/-/platform-1.3.1.tgz";
        sha1 = "492210892335bd3131c0a08dda2d93ec3543e423";
      };
    };
    "dashify-0.2.2" = {
      name = "dashify";
      packageName = "dashify";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashify/-/dashify-0.2.2.tgz";
        sha1 = "6a07415a01c91faf4a32e38d9dfba71f61cb20fe";
      };
    };
    "jws-3.1.4" = {
      name = "jws";
      packageName = "jws";
      version = "3.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/jws/-/jws-3.1.4.tgz";
        sha1 = "f9e8b9338e8a847277d6444b1464f61880e050a2";
      };
    };
    "lodash.includes-4.3.0" = {
      name = "lodash.includes";
      packageName = "lodash.includes";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.includes/-/lodash.includes-4.3.0.tgz";
        sha1 = "60bb98a87cb923c68ca1e51325483314849f553f";
      };
    };
    "lodash.isboolean-3.0.3" = {
      name = "lodash.isboolean";
      packageName = "lodash.isboolean";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isboolean/-/lodash.isboolean-3.0.3.tgz";
        sha1 = "6c2e171db2a257cd96802fd43b01b20d5f5870f6";
      };
    };
    "lodash.isinteger-4.0.4" = {
      name = "lodash.isinteger";
      packageName = "lodash.isinteger";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isinteger/-/lodash.isinteger-4.0.4.tgz";
        sha1 = "619c0af3d03f8b04c31f5882840b77b11cd68343";
      };
    };
    "lodash.isnumber-3.0.3" = {
      name = "lodash.isnumber";
      packageName = "lodash.isnumber";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isnumber/-/lodash.isnumber-3.0.3.tgz";
        sha1 = "3ce76810c5928d03352301ac287317f11c0b1ffc";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "lodash.once-4.1.1" = {
      name = "lodash.once";
      packageName = "lodash.once";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz";
        sha1 = "0dd3971213c7c56df880977d504c88fb471a97ac";
      };
    };
    "base64url-2.0.0" = {
      name = "base64url";
      packageName = "base64url";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64url/-/base64url-2.0.0.tgz";
        sha1 = "eac16e03ea1438eff9423d69baa36262ed1f70bb";
      };
    };
    "jwa-1.1.5" = {
      name = "jwa";
      packageName = "jwa";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jwa/-/jwa-1.1.5.tgz";
        sha1 = "a0552ce0220742cd52e153774a32905c30e756e5";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "buffer-equal-constant-time-1.0.1" = {
      name = "buffer-equal-constant-time";
      packageName = "buffer-equal-constant-time";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz";
        sha1 = "f8e71132f7ffe6e01a5c9697a4c6f3e48d5cc819";
      };
    };
    "ecdsa-sig-formatter-1.0.9" = {
      name = "ecdsa-sig-formatter";
      packageName = "ecdsa-sig-formatter";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.9.tgz";
        sha1 = "4bc926274ec3b5abb5016e7e1d60921ac262b2a1";
      };
    };
    "mime-db-1.24.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.24.0.tgz";
        sha1 = "e2d13f939f0016c6e4e9ad25a8652f126c467f0c";
      };
    };
    "basic-auth-1.1.0" = {
      name = "basic-auth";
      packageName = "basic-auth";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/basic-auth/-/basic-auth-1.1.0.tgz";
        sha1 = "45221ee429f7ee1e5035be3f51533f1cdfd29884";
      };
    };
    "debug-2.6.8" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.8.tgz";
        sha1 = "e731531ca2ede27d188222427da17821d68ff4fc";
      };
    };
    "tdigest-0.1.1" = {
      name = "tdigest";
      packageName = "tdigest";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tdigest/-/tdigest-0.1.1.tgz";
        sha1 = "2e3cb2c39ea449e55d1e6cd91117accca4588021";
      };
    };
    "bintrees-1.0.1" = {
      name = "bintrees";
      packageName = "bintrees";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bintrees/-/bintrees-1.0.1.tgz";
        sha1 = "0e655c9b9c2435eaab68bf4027226d2b55a34524";
      };
    };
    "@purest/config-1.0.1" = {
      name = "@purest/config";
      packageName = "@purest/config";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@purest/config/-/config-1.0.1.tgz";
        sha512 = "2ibcx8avydpp33likhgw3n859r9jfwhvcszkxg57aggb3vsxm4nn1vizbsnrd6vikj3ilhxg5z4122fp4vb5iss96wsvsgn8m9vnhbh";
      };
    };
    "@request/api-0.6.0" = {
      name = "@request/api";
      packageName = "@request/api";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@request/api/-/api-0.6.0.tgz";
        sha1 = "e46e4c32e21db9ca72639701cba1ebfee06c1666";
      };
    };
    "@request/interface-0.1.0" = {
      name = "@request/interface";
      packageName = "@request/interface";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@request/interface/-/interface-0.1.0.tgz";
        sha1 = "c913504d3dc2810afad555b599aeaec2cc4c6768";
      };
    };
    "double-ended-queue-2.1.0-0" = {
      name = "double-ended-queue";
      packageName = "double-ended-queue";
      version = "2.1.0-0";
      src = fetchurl {
        url = "https://registry.npmjs.org/double-ended-queue/-/double-ended-queue-2.1.0-0.tgz";
        sha1 = "103d3527fd31528f40188130c841efdd78264e5c";
      };
    };
    "redis-commands-1.3.1" = {
      name = "redis-commands";
      packageName = "redis-commands";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-commands/-/redis-commands-1.3.1.tgz";
        sha1 = "81d826f45fa9c8b2011f4cd7a0fe597d241d442b";
      };
    };
    "redis-parser-2.6.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-2.6.0.tgz";
        sha1 = "52ed09dacac108f1a631c07e9b69941e7a19504b";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "form-data-2.3.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.1.tgz";
        sha1 = "6fb94fbd71885306d73d15cc497fe4cc4ecd44bf";
      };
    };
    "har-validator-5.0.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.0.3.tgz";
        sha1 = "ba402c266194f15956ef15e0fcf242993f6a7dfd";
      };
    };
    "hawk-6.0.2" = {
      name = "hawk";
      packageName = "hawk";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-6.0.2.tgz";
        sha512 = "1nl2hjr2mnhj5jlaz8mh54z7acwz5j5idkch04qgjk78756gw5d0fjk4a2immil5ij9ijdssb9ndpryvnh2xpcbgcjv8lxybn330als";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "qs-6.5.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.1.tgz";
        sha512 = "3waqapyj1k4g135sgj636rmswiaixq19is1rw0rpv4qp6k7dl0a9nwy06m7yl5lbdk9p6xpwwngnggbzlzaz6rh11c86j2nvnnf273r";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "ajv-5.3.0" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.3.0.tgz";
        sha1 = "4414ff74a50879c208ee5fdc826e32c303549eda";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "fast-deep-equal-1.0.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.0.0.tgz";
        sha1 = "96256a3bc975595eb36d82e9929d060d893439ff";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "hoek-4.2.0" = {
      name = "hoek";
      packageName = "hoek";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-4.2.0.tgz";
        sha512 = "2cz0q3nnv67drgaw2rm7q57r9rgdax1qa0n4z46is7db1w8vwmh574xcr0d73xl5lg80vb85xg2gdhxzh9gbllagp7xk2q228pw4idz";
      };
    };
    "boom-4.3.1" = {
      name = "boom";
      packageName = "boom";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-4.3.1.tgz";
        sha1 = "4f8a3005cb4a7e3889f749030fd25b96e01d2e31";
      };
    };
    "cryptiles-3.1.2" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-3.1.2.tgz";
        sha1 = "a89fbb220f5ce25ec56e8c4aa8a4fd7b5b0d29fe";
      };
    };
    "sntp-2.1.0" = {
      name = "sntp";
      packageName = "sntp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-2.1.0.tgz";
        sha512 = "0k2smmr24w5hb1cpql6vcgh58vzp4pmh9anf0bgz3arlsgq1mapnlq9fjqr6xs10aq1cmxaw987fwknqi62frax0fvs9bj3q3kmpg8l";
      };
    };
    "boom-5.2.0" = {
      name = "boom";
      packageName = "boom";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-5.2.0.tgz";
        sha512 = "19h20yqpvca08dns1rs4f057f10w63v0snxfml4h5khsk266x3x1im0w72bza4k2xn0kfz6jlv001dhcvxsjr09bmbqnysils9m7437";
      };
    };
    "resolve-url-0.2.1" = {
      name = "resolve-url";
      packageName = "resolve-url";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-url/-/resolve-url-0.2.1.tgz";
        sha1 = "2c637fe77c893afd2a663fe21aa9080068e2052a";
      };
    };
    "options-0.0.6" = {
      name = "options";
      packageName = "options";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/options/-/options-0.0.6.tgz";
        sha1 = "ec22d312806bb53e731773e7cdaefcf1c643128f";
      };
    };
    "ultron-1.0.2" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz";
        sha1 = "ace116ab557cd197386a4e88f4685378c8b2e4fa";
      };
    };
  };
  args = {
    name = "uppy-server";
    packageName = "uppy-server";
    version = "0.8.0";
    src = ./.;
    dependencies = [
      sources."@purest/providers-1.0.0"
      sources."atob-2.0.3"
      (sources."aws-sdk-2.145.0" // {
        dependencies = [
          sources."uuid-3.1.0"
        ];
      })
      sources."body-parser-1.15.2"
      sources."commander-2.9.0"
      (sources."connect-redis-3.3.2" // {
        dependencies = [
          sources."debug-3.1.0"
        ];
      })
      sources."cookie-parser-1.4.3"
      sources."express-4.14.0"
      sources."express-prom-bundle-3.2.1"
      sources."express-session-1.14.2"
      sources."grant-express-3.7.0"
      sources."helmet-3.3.0"
      sources."jsonwebtoken-8.1.0"
      sources."lodash.merge-4.6.0"
      (sources."mime-types-2.1.12" // {
        dependencies = [
          sources."mime-db-1.24.0"
        ];
      })
      (sources."morgan-1.8.2" // {
        dependencies = [
          sources."debug-2.6.8"
        ];
      })
      sources."ms-2.0.0"
      sources."prom-client-10.2.2"
      sources."purest-3.0.0"
      sources."redis-2.8.0"
      (sources."request-2.83.0" // {
        dependencies = [
          sources."aws-sign2-0.7.0"
          sources."caseless-0.12.0"
          sources."form-data-2.3.1"
          sources."har-validator-5.0.3"
          sources."hawk-6.0.2"
          sources."http-signature-1.2.0"
          sources."mime-types-2.1.17"
          sources."qs-6.5.1"
          sources."tunnel-agent-0.6.0"
          sources."uuid-3.1.0"
          sources."hoek-4.2.0"
          sources."boom-4.3.1"
          (sources."cryptiles-3.1.2" // {
            dependencies = [
              sources."boom-5.2.0"
            ];
          })
          sources."sntp-2.1.0"
          sources."assert-plus-1.0.0"
        ];
      })
      sources."tus-js-client-1.4.3"
      sources."uuid-2.0.2"
      sources."validator-9.1.1"
      sources."ws-1.1.1"
      sources."buffer-4.9.1"
      sources."crypto-browserify-1.0.9"
      sources."events-1.1.1"
      sources."jmespath-0.15.0"
      sources."querystring-0.2.0"
      sources."sax-1.2.1"
      sources."url-0.10.3"
      sources."xml2js-0.4.17"
      sources."xmlbuilder-4.2.1"
      sources."base64-js-1.2.1"
      sources."ieee754-1.1.8"
      sources."isarray-1.0.0"
      sources."punycode-1.3.2"
      sources."lodash-4.17.4"
      sources."bytes-2.4.0"
      sources."content-type-1.0.4"
      (sources."debug-2.2.0" // {
        dependencies = [
          sources."ms-0.7.1"
        ];
      })
      sources."depd-1.1.1"
      sources."http-errors-1.5.1"
      sources."iconv-lite-0.4.13"
      sources."on-finished-2.3.0"
      sources."qs-6.2.0"
      sources."raw-body-2.1.7"
      (sources."type-is-1.6.15" // {
        dependencies = [
          sources."mime-types-2.1.17"
        ];
      })
      sources."inherits-2.0.3"
      sources."setprototypeof-1.0.2"
      sources."statuses-1.4.0"
      sources."ee-first-1.1.1"
      sources."unpipe-1.0.0"
      sources."media-typer-0.3.0"
      sources."mime-db-1.30.0"
      sources."graceful-readlink-1.0.1"
      sources."cookie-0.3.1"
      sources."cookie-signature-1.0.6"
      (sources."accepts-1.3.4" // {
        dependencies = [
          sources."mime-types-2.1.17"
        ];
      })
      sources."array-flatten-1.1.1"
      sources."content-disposition-0.5.1"
      sources."encodeurl-1.0.1"
      sources."escape-html-1.0.3"
      sources."etag-1.7.0"
      (sources."finalhandler-0.5.0" // {
        dependencies = [
          sources."statuses-1.3.1"
        ];
      })
      sources."fresh-0.3.0"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      sources."parseurl-1.3.2"
      sources."path-to-regexp-0.1.7"
      sources."proxy-addr-1.1.5"
      sources."range-parser-1.2.0"
      (sources."send-0.14.1" // {
        dependencies = [
          sources."ms-0.7.1"
          sources."statuses-1.3.1"
        ];
      })
      (sources."serve-static-1.11.2" // {
        dependencies = [
          sources."send-0.14.2"
          sources."ms-0.7.2"
          sources."statuses-1.3.1"
        ];
      })
      sources."utils-merge-1.0.0"
      sources."vary-1.1.2"
      sources."negotiator-0.6.1"
      sources."forwarded-0.1.2"
      sources."ipaddr.js-1.4.0"
      sources."destroy-1.0.4"
      sources."mime-1.3.4"
      sources."url-value-parser-1.0.0"
      sources."crc-3.4.1"
      sources."on-headers-1.0.1"
      sources."uid-safe-2.1.5"
      sources."random-bytes-1.0.0"
      (sources."grant-3.7.0" // {
        dependencies = [
          sources."request-2.74.0"
          sources."qs-6.2.1"
        ];
      })
      sources."deep-copy-1.4.0"
      sources."aws-sign2-0.6.0"
      sources."aws4-1.6.0"
      sources."bl-1.1.2"
      sources."caseless-0.11.0"
      sources."combined-stream-1.0.5"
      sources."extend-3.0.1"
      sources."forever-agent-0.6.1"
      sources."form-data-1.0.1"
      sources."har-validator-2.0.6"
      sources."hawk-3.1.3"
      sources."http-signature-1.1.1"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."json-stringify-safe-5.0.1"
      sources."node-uuid-1.4.8"
      sources."oauth-sign-0.8.2"
      sources."stringstream-0.0.5"
      (sources."tough-cookie-2.3.3" // {
        dependencies = [
          sources."punycode-1.4.1"
        ];
      })
      sources."tunnel-agent-0.4.3"
      sources."readable-stream-2.0.6"
      sources."core-util-is-1.0.2"
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-0.10.31"
      sources."util-deprecate-1.0.2"
      sources."delayed-stream-1.0.0"
      sources."async-2.5.0"
      sources."chalk-1.1.3"
      sources."is-my-json-valid-2.16.1"
      sources."pinkie-promise-2.0.1"
      sources."ansi-styles-2.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."ansi-regex-2.1.1"
      sources."generate-function-2.0.0"
      sources."generate-object-property-1.2.0"
      sources."jsonpointer-4.0.1"
      sources."xtend-4.0.1"
      sources."is-property-1.0.2"
      sources."pinkie-2.0.4"
      sources."hoek-2.16.3"
      sources."boom-2.10.1"
      sources."cryptiles-2.0.5"
      sources."sntp-1.0.9"
      sources."assert-plus-0.2.0"
      (sources."jsprim-1.4.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."sshpk-1.13.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."extsprintf-1.3.0"
      sources."json-schema-0.2.3"
      (sources."verror-1.10.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."asn1-0.2.3"
      (sources."dashdash-1.14.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."getpass-0.1.7" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."jsbn-0.1.1"
      sources."tweetnacl-0.14.5"
      sources."ecc-jsbn-0.1.1"
      sources."bcrypt-pbkdf-1.0.1"
      sources."connect-3.5.0"
      sources."dns-prefetch-control-0.1.0"
      sources."dont-sniff-mimetype-1.0.0"
      sources."frameguard-3.0.0"
      sources."helmet-csp-2.2.0"
      sources."hide-powered-by-1.0.0"
      sources."hpkp-2.0.0"
      sources."hsts-2.0.0"
      sources."ienoopen-1.0.0"
      sources."nocache-2.0.0"
      sources."referrer-policy-1.1.0"
      sources."x-xss-protection-1.0.0"
      sources."camelize-1.0.0"
      sources."content-security-policy-builder-1.1.0"
      sources."dasherize-2.0.0"
      sources."lodash.reduce-4.6.0"
      sources."platform-1.3.1"
      sources."dashify-0.2.2"
      sources."jws-3.1.4"
      sources."lodash.includes-4.3.0"
      sources."lodash.isboolean-3.0.3"
      sources."lodash.isinteger-4.0.4"
      sources."lodash.isnumber-3.0.3"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.once-4.1.1"
      sources."base64url-2.0.0"
      sources."jwa-1.1.5"
      sources."safe-buffer-5.1.1"
      sources."buffer-equal-constant-time-1.0.1"
      sources."ecdsa-sig-formatter-1.0.9"
      sources."basic-auth-1.1.0"
      sources."tdigest-0.1.1"
      sources."bintrees-1.0.1"
      sources."@purest/config-1.0.1"
      sources."@request/api-0.6.0"
      sources."@request/interface-0.1.0"
      sources."double-ended-queue-2.1.0-0"
      sources."redis-commands-1.3.1"
      sources."redis-parser-2.6.0"
      sources."performance-now-2.1.0"
      sources."asynckit-0.4.0"
      sources."ajv-5.3.0"
      sources."har-schema-2.0.0"
      sources."co-4.6.0"
      sources."fast-deep-equal-1.0.0"
      sources."fast-json-stable-stringify-2.0.0"
      sources."json-schema-traverse-0.3.1"
      sources."resolve-url-0.2.1"
      sources."options-0.0.6"
      sources."ultron-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Almost as cute as a Puppy :dog:";
      homepage = "https://github.com/transloadit/uppy-server#readme";
      license = "ISC";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}