apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uppy-server-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: uppy-server
    spec:
      containers:
      - name: uppy-server
        image: docker.io/transloadit/uppy-server:latest
        ports:
        - containerPort: 3020
        envFrom:
        - configMapRef:
            name: uppy-server-env
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60    
